version: '3.8'
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"  # Exposes Ollama on port 11434
    volumes:
      - ollama_data:/root/.ollama  # Persistent storage for models
    environment:
      - OLLAMA_HOST=0.0.0.0:11434  # Allows external access if needed

volumes:
  ollama_data:
